title: Tabler - Admin panel made simple
description: Premium dashboard template with responsive and high quality UI. For Free!

port: 4001
highlighter: rouge

exclude:
- gulpfile.js
- package-lock.json
- package.json
- node_modules
- .idea/

github_url: https://github.com/tabler/tabler
download_url: https://github.com/tabler/tabler/archive/master.zip
demo_url: https://codecalm.net/tabler/